// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: base/tx_ingress/v1/transaction_ingress.proto

package txingressv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TransactionIngressService_Submit_FullMethodName = "/base.tx_ingress.v1.TransactionIngressService/Submit"
)

// TransactionIngressServiceClient is the client API for TransactionIngressService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Accepts raw transactions over a persistent bidirectional stream.
type TransactionIngressServiceClient interface {
	// Submits transactions independently and returns results as they complete.
	Submit(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SubmitRequest, SubmitResponse], error)
}

type transactionIngressServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionIngressServiceClient(cc grpc.ClientConnInterface) TransactionIngressServiceClient {
	return &transactionIngressServiceClient{cc}
}

func (c *transactionIngressServiceClient) Submit(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SubmitRequest, SubmitResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TransactionIngressService_ServiceDesc.Streams[0], TransactionIngressService_Submit_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubmitRequest, SubmitResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TransactionIngressService_SubmitClient = grpc.BidiStreamingClient[SubmitRequest, SubmitResponse]

// TransactionIngressServiceServer is the server API for TransactionIngressService service.
// All implementations must embed UnimplementedTransactionIngressServiceServer
// for forward compatibility.
//
// Accepts raw transactions over a persistent bidirectional stream.
type TransactionIngressServiceServer interface {
	// Submits transactions independently and returns results as they complete.
	Submit(grpc.BidiStreamingServer[SubmitRequest, SubmitResponse]) error
	mustEmbedUnimplementedTransactionIngressServiceServer()
}

// UnimplementedTransactionIngressServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransactionIngressServiceServer struct{}

func (UnimplementedTransactionIngressServiceServer) Submit(grpc.BidiStreamingServer[SubmitRequest, SubmitResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Submit not implemented")
}
func (UnimplementedTransactionIngressServiceServer) mustEmbedUnimplementedTransactionIngressServiceServer() {
}
func (UnimplementedTransactionIngressServiceServer) testEmbeddedByValue() {}

// UnsafeTransactionIngressServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionIngressServiceServer will
// result in compilation errors.
type UnsafeTransactionIngressServiceServer interface {
	mustEmbedUnimplementedTransactionIngressServiceServer()
}

func RegisterTransactionIngressServiceServer(s grpc.ServiceRegistrar, srv TransactionIngressServiceServer) {
	// If the following call pancis, it indicates UnimplementedTransactionIngressServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransactionIngressService_ServiceDesc, srv)
}

func _TransactionIngressService_Submit_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TransactionIngressServiceServer).Submit(&grpc.GenericServerStream[SubmitRequest, SubmitResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TransactionIngressService_SubmitServer = grpc.BidiStreamingServer[SubmitRequest, SubmitResponse]

// TransactionIngressService_ServiceDesc is the grpc.ServiceDesc for TransactionIngressService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionIngressService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "base.tx_ingress.v1.TransactionIngressService",
	HandlerType: (*TransactionIngressServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Submit",
			Handler:       _TransactionIngressService_Submit_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "base/tx_ingress/v1/transaction_ingress.proto",
}
