// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: base/tx_ingress/v1/transaction_ingress.proto

package txingressv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// One raw transaction submission.
type SubmitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stream-local identifier echoed in the result.
	RequestId uint64 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// EIP-2718 encoded signed transaction.
	RawTransaction []byte `protobuf:"bytes,2,opt,name=raw_transaction,json=rawTransaction,proto3" json:"raw_transaction,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubmitRequest) Reset() {
	*x = SubmitRequest{}
	mi := &file_base_tx_ingress_v1_transaction_ingress_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRequest) ProtoMessage() {}

func (x *SubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_tx_ingress_v1_transaction_ingress_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRequest.ProtoReflect.Descriptor instead.
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return file_base_tx_ingress_v1_transaction_ingress_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *SubmitRequest) GetRawTransaction() []byte {
	if x != nil {
		return x.RawTransaction
	}
	return nil
}

// Admission result for one submission.
type SubmitResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier from the corresponding submission.
	RequestId uint64 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Admission success or rejection.
	//
	// Types that are valid to be assigned to Outcome:
	//
	//	*SubmitResponse_TransactionHash
	//	*SubmitResponse_Error
	Outcome       isSubmitResponse_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResponse) Reset() {
	*x = SubmitResponse{}
	mi := &file_base_tx_ingress_v1_transaction_ingress_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponse) ProtoMessage() {}

func (x *SubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_base_tx_ingress_v1_transaction_ingress_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponse.ProtoReflect.Descriptor instead.
func (*SubmitResponse) Descriptor() ([]byte, []int) {
	return file_base_tx_ingress_v1_transaction_ingress_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitResponse) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *SubmitResponse) GetOutcome() isSubmitResponse_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *SubmitResponse) GetTransactionHash() []byte {
	if x != nil {
		if x, ok := x.Outcome.(*SubmitResponse_TransactionHash); ok {
			return x.TransactionHash
		}
	}
	return nil
}

func (x *SubmitResponse) GetError() *SubmitError {
	if x != nil {
		if x, ok := x.Outcome.(*SubmitResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isSubmitResponse_Outcome interface {
	isSubmitResponse_Outcome()
}

type SubmitResponse_TransactionHash struct {
	// Hash of a transaction accepted by the mempool node.
	TransactionHash []byte `protobuf:"bytes,2,opt,name=transaction_hash,json=transactionHash,proto3,oneof"`
}

type SubmitResponse_Error struct {
	// JSON-RPC-compatible transaction rejection.
	Error *SubmitError `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*SubmitResponse_TransactionHash) isSubmitResponse_Outcome() {}

func (*SubmitResponse_Error) isSubmitResponse_Outcome() {}

// JSON-RPC-compatible error returned for a rejected transaction.
type SubmitError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON-RPC error code.
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// JSON-RPC error message.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Raw JSON-RPC error data, when present.
	JsonData      []byte `protobuf:"bytes,3,opt,name=json_data,json=jsonData,proto3,oneof" json:"json_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitError) Reset() {
	*x = SubmitError{}
	mi := &file_base_tx_ingress_v1_transaction_ingress_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitError) ProtoMessage() {}

func (x *SubmitError) ProtoReflect() protoreflect.Message {
	mi := &file_base_tx_ingress_v1_transaction_ingress_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitError.ProtoReflect.Descriptor instead.
func (*SubmitError) Descriptor() ([]byte, []int) {
	return file_base_tx_ingress_v1_transaction_ingress_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SubmitError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SubmitError) GetJsonData() []byte {
	if x != nil {
		return x.JsonData
	}
	return nil
}

var File_base_tx_ingress_v1_transaction_ingress_proto protoreflect.FileDescriptor

const file_base_tx_ingress_v1_transaction_ingress_proto_rawDesc = "" +
	"\n" +
	",base/tx_ingress/v1/transaction_ingress.proto\x12\x12base.tx_ingress.v1\"W\n" +
	"\rSubmitRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12'\n" +
	"\x0fraw_transaction\x18\x02 \x01(\fR\x0erawTransaction\"\xa0\x01\n" +
	"\x0eSubmitResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12+\n" +
	"\x10transaction_hash\x18\x02 \x01(\fH\x00R\x0ftransactionHash\x127\n" +
	"\x05error\x18\x03 \x01(\v2\x1f.base.tx_ingress.v1.SubmitErrorH\x00R\x05errorB\t\n" +
	"\aoutcome\"k\n" +
	"\vSubmitError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12 \n" +
	"\tjson_data\x18\x03 \x01(\fH\x00R\bjsonData\x88\x01\x01B\f\n" +
	"\n" +
	"_json_data2p\n" +
	"\x19TransactionIngressService\x12S\n" +
	"\x06Submit\x12!.base.tx_ingress.v1.SubmitRequest\x1a\".base.tx_ingress.v1.SubmitResponse(\x010\x01BJZHgithub.com/ethereum-optimism/infra/proxyd/base/tx_ingress/v1;txingressv1b\x06proto3"

var (
	file_base_tx_ingress_v1_transaction_ingress_proto_rawDescOnce sync.Once
	file_base_tx_ingress_v1_transaction_ingress_proto_rawDescData []byte
)

func file_base_tx_ingress_v1_transaction_ingress_proto_rawDescGZIP() []byte {
	file_base_tx_ingress_v1_transaction_ingress_proto_rawDescOnce.Do(func() {
		file_base_tx_ingress_v1_transaction_ingress_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_base_tx_ingress_v1_transaction_ingress_proto_rawDesc), len(file_base_tx_ingress_v1_transaction_ingress_proto_rawDesc)))
	})
	return file_base_tx_ingress_v1_transaction_ingress_proto_rawDescData
}

var file_base_tx_ingress_v1_transaction_ingress_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_base_tx_ingress_v1_transaction_ingress_proto_goTypes = []any{
	(*SubmitRequest)(nil),  // 0: base.tx_ingress.v1.SubmitRequest
	(*SubmitResponse)(nil), // 1: base.tx_ingress.v1.SubmitResponse
	(*SubmitError)(nil),    // 2: base.tx_ingress.v1.SubmitError
}
var file_base_tx_ingress_v1_transaction_ingress_proto_depIdxs = []int32{
	2, // 0: base.tx_ingress.v1.SubmitResponse.error:type_name -> base.tx_ingress.v1.SubmitError
	0, // 1: base.tx_ingress.v1.TransactionIngressService.Submit:input_type -> base.tx_ingress.v1.SubmitRequest
	1, // 2: base.tx_ingress.v1.TransactionIngressService.Submit:output_type -> base.tx_ingress.v1.SubmitResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_base_tx_ingress_v1_transaction_ingress_proto_init() }
func file_base_tx_ingress_v1_transaction_ingress_proto_init() {
	if File_base_tx_ingress_v1_transaction_ingress_proto != nil {
		return
	}
	file_base_tx_ingress_v1_transaction_ingress_proto_msgTypes[1].OneofWrappers = []any{
		(*SubmitResponse_TransactionHash)(nil),
		(*SubmitResponse_Error)(nil),
	}
	file_base_tx_ingress_v1_transaction_ingress_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_base_tx_ingress_v1_transaction_ingress_proto_rawDesc), len(file_base_tx_ingress_v1_transaction_ingress_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_base_tx_ingress_v1_transaction_ingress_proto_goTypes,
		DependencyIndexes: file_base_tx_ingress_v1_transaction_ingress_proto_depIdxs,
		MessageInfos:      file_base_tx_ingress_v1_transaction_ingress_proto_msgTypes,
	}.Build()
	File_base_tx_ingress_v1_transaction_ingress_proto = out.File
	file_base_tx_ingress_v1_transaction_ingress_proto_goTypes = nil
	file_base_tx_ingress_v1_transaction_ingress_proto_depIdxs = nil
}
